version: '3'

services:
  windowscontainer:
    image: windowscontainer
    build:
      context: ./WindowsContainer
      dockerfile: Dockerfile
    depends_on:
      - sql.data
  sql.data:
    image: microsoft/mssql-server-windows-express:latest